config/routes.rb
require "heartbeat/application"

Mobis::Application.routes.draw do
  get "home/new"
  get "home/index"
  get "home/about"
  get "home/contact"

  root :to => "home#index"
  
  match "set_js_vars" => "application#set_js_vars", :as => "set_js_vars", :via => :post
  match "get_js_var" => "application#get_js_var", :as => "get_js_var", :via => :post 
  match ":username/katalog" => "catalogues#index", :as => "catalogue"  
  match "unauthorized_access" => "application#unauthorized_access"
  match "show_error" => "application#show_error"
  match "poruke" => "messages#index", :as => "messages"
  match "mobiteli" => "phones#index", :as => "phones"
  
  devise_scope :account do    
    match "registracija" => "accounts/registrations#index", :as => "register", :via => :get
    match "registracija_korisnika" => "accounts/registrations#new", :account => { :type => "user" }, :as => "register_user"
    match "registracija_prodavnice" => "accounts/registrations#new", :account => { :type => "store" }, :as => "register_store"
    match "registracija" => "accounts/registrations#create", :as => "registration", :method => :post  
  
  end
  
  devise_for :accounts, :controllers => {
    :sessions => "accounts/sessions",
    :passwords => "devise/passwords"
  },
  :path => "",
  :path_names => {:sign_in => "prijava", :sign_out => "odjava", :new_unlock => "promijeni_sifru"}
  
  namespace :api do
    namespace :v1 do      
      match "chat/config" => "chat#get_conf", via: :get
      
      mount Api::V1::Phones, :at => "/mobiteli"
      mount Api::V1::Messages, :at => "/poruke"
      mount Api::V1::Catalogue, :at => "/katalog"
    end
  end
  
  namespace :admin do
    match "korisnici" => "users#list_users", :as => "users"
    match "users/lock" => "users#lock_user", via: :post
    
    resources :phones, :only => [:new, :edit, :create, :update, :destroy]
    match "phones/add/:id" => "phones#add", via: :post, :as => "phone_add"
    match "mobiteli" => "phones#list_phones", via: :get, :as => "phones"
    match "mobiteli/atributi" => "phones#attributes", via: :get, :as => "phones_attributes"
    match "phones_add_attribute" => "phones#add_attribute", via: :post
    match "mobiteli/import" => "phones#import_phones", via: :get
    match "phones/import" => "phones#import", via: :post, :as => "phones_import_phones"
    match "phones/import_images" => "phones#import_images", via: :post
    match "mobiteli/reindex" => "phones#reindex", via: :get, :as => "phones_reindex"
    
    resource :phones, :only => [:create, :new] 
  end
  
  resources :phones, :only => [:show]
  resources :comments, :only => [:create] do
    collection do
      match "show_next_page", :action => "show_next_page", :via => :post
      get "new/:phone_id", :action => "new"
    end
    member do
      post "", :action => "create"
    end
  end
  
  resource :reviews, :only => [] do
    member do
      post "create_phone_review", :action => "create_phone_review"
    end
  end
  
  resource :catalogue, :only => [:new, :update, :edit] do
    match "show_next_page", :action => "show_next_page", :via => :post
    match "pre_remove", :action => "pre_remove"
    match "remove", :action => "remove", via: :post
    match "phone_details_remote", :action => "phone_details_remote", via: :post
  end
  
  resource :message, :only => [:index, :new, :create, :update, :edit] do
    match "/:type/:id", :action => "show", :via => "get"
    match "show_next_page", :action => "show_next_page", :via => :post
    match "bulk_delete", :action => "bulk_delete", :via => :post
    match "receiver_id_remote", :action => "receiver_id_remote", :via => :post
    match "pre_remove", :action => "pre_remove", :via => "post"
    match "remove", :action => "remove", :via => "post"
    match "reply", :action => "reply", :via => "post"
  end
  
  resource :search, :only => [:index], :controller => "search" do
    collection do
      get "index"
      post "index"
      get "search_phones"
      post "search_phones"
      get "advanced_search"
      post "advanced_search"
    end
  end
    
  match "/postavke" => "accounts#show", :as => "settings", :via => "get"
  match "/remove_settings" => "accounts#remove", :as => "settings_remove", :via => :delete
  match "/add_settings" => "accounts#add", :as => "settings_add", :via => :put
  match "/change_password" => "accounts#change_password", :as => "change_password", :via => :post
  match "/accounts_details" => "accounts#accounts_details", :as => "accounts_details", :via => :post  
  match "settings/change_avatar" => "accounts#change_avatar", :as => "change_avatar", :via => :post
 
  match "mobiteli/:brand" => "phones#index", :as => "brand", :via => "get"
  
  mount Heartbeat::Application, :at => "/heartbeat"  
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Paperclip
  
  include Comparable
  
  field :text, :type => String
  field :date_sent, :type => DateTime 
  field :date_read, :type => DateTime 
  field :auto_generated, :type => Boolean
  field :context, :type => Hash # not used for now
  field :sender_id, :type => String
  field :receiver_id, :type => String
  field :mark_deleted, :type => Boolean, :default => false
  
  field :sender_details, :type => Hash
  field :receiver_details, :type => Hash
  
  field :reply_to, :type => String
  field :reply_to_type, :type => String
  field :responded_with, :type => String 
  field :responded_with_type, :type => String
  
  embedded_in :sender, class_name: "Account", inverse_of: :sent_messages
  embedded_in :receiver, class_name: "Account", inverse_of: :received_messages
  
  #TODO: attachments stored as Moped::BSON::Binary as byte array with limit in size
  
  validates :text, :presence => true, length: {minimum: 10}
  validates :sender_id, :presence => true
  validates :receiver_id, :presence => true
  
  SUBJECT_ATTRS = ["id", "avatar", "name", "website", "phone", "address"]
  DEFAULT_LOGO = "/images/no_image.jpg"
  before_create do |message|
    message.date_sent = Time.now.utc.to_time.to_i unless message.date_sent
    
    ### Setting source and target attributes
    puts "Setting source and target"
    
    sen_acc = Account.find(self.sender_id)
    sen = sen_acc.rolable
    sen_rec = Account.find(self.receiver_id)
    rec = sen_rec.rolable
    
    self.sender_details = {"username" => sen_acc.username}
    self.receiver_details = {"username" => sen_rec.username}
    SUBJECT_ATTRS.each do |attr|
      if sen.respond_to?(attr)      
        if attr == "avatar"
          val_sen = sen.avatar.exists? ? sen.avatar.url : DEFAULT_LOGO
        else
          val_sen = sen.send(attr)
        end
        self.sender_details[attr] = val_sen
      end
      
      if rec.respond_to?(attr) 
        if attr == "avatar"
          val_rec = rec.avatar.exists? ? rec.avatar.url : DEFAULT_LOGO
          puts "receiver logo #{val_rec.inspect}"
        else
          val_rec = rec.send(attr)
        end
        self.receiver_details[attr] = val_rec
      end
    end
  end
  
  before_save do |message|
    message.date_sent = message.date_sent.to_time.utc.to_i if message.date_sent
    message.date_read = message.date_read.to_time.utc.to_i if message.date_read
  end
  
  def sort_unread(other)
    return 1 if self.date_read.nil? && !other.date_read.nil?
    return -1 if !self.date_read.nil? && other.date_read.nil?
    0
  end
  
  def to_hash
    res = self.attributes.with_indifferent_access
    res
  end
end

app/controllers/api/V1/messages.rb
module Api
  module V1
    class Messages < Base
      get "/received" do
        require_authorization
        
        get_messages(:received).to_json
      end
      
      get "/sent" do 
        require_authorization
        
        get_messages(:sent).to_json
      end
      
      post "/" do
        require_authorization
        
        receiver_id = parameters[:to] || nil
        text = parameters[:text] || nil
        reply_to = parameters[:reply_to] || nil
        
        halt 400, "to and text are required" if receiver_id.blank? || text.blank?
        
        result = Managers::MessageManager.send_message(@account, receiver_id, text, {:reply_to => reply_to})
        halt 400, result[:text] unless result[:status]
        
        MessageDecorator.decorate(result[:message]).get_hash.to_json
      end
      
      
      get "/*" do
        require_authorization
        
        message_id = params[:splat].first
        type = parameters[:type] || nil
                
        conversation = Managers::MessageManager.get_conversation(@account, type, message_id)        
        halt 400, "Conversation not found" if conversation.empty? || (conversation.is_a?(Hash) && !conversation[:status])
        
        target_message = conversation.select{|m| m.id.to_s == message_id }.to_a.first
        other_part = type.to_s == "received" ? target_message.sender_id : target_message.receiver_id
        
        read_result = target_message.date_read.nil? ? Managers::MessageManager.read_message(@account, target_message) : nil
        
        response = {}
        response[:messages] = conversation.map! { |message| MessageDecorator.decorate(message).get_hash }
        response.to_json
      end
      
      private
      def get_messages(type)
        from = parameters[:from] ? parameters[:from].to_i : 0
        to = parameters[:to] ? parameters[:to].to_i : nil
        
        received = Managers::MessageManager.get_messages(@account, type.to_sym, {:search_term => parameters[:search_term] || nil, :from => from, :to => to, :sort_by => "date"})
        inbox = received[:related]
        unread_count = received[:unread_count]
        inbox_to = received[:to]
        
        response = {:from => from, :to => inbox_to, :unread_count => unread_count}
        response[:messages] = inbox.map { |message| MessageDecorator.decorate(message).get_hash }
        response
      end
  
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :only_signed_in_users
  
  def index
    @received = Managers::MessageManager.get_messages(current_account, :received, {:search_term => nil, :from => 0, :to => 2, :sort_by => "date"})
    @sent = Managers::MessageManager.get_messages(current_account, :sent, {:search_term => nil, :from => 0, :to => 2, :sort_by => "date"})
    
    @inbox = @received[:related]
    @outbox = @sent[:related]
    @unread_count = @received[:unread_count]
    @inbox_to = @received[:to]
    @outbox_to = @sent[:to]
    
    if @inbox.empty?
      @receivers_usernames = Account.all.select {|a| a.id.to_s != current_account.id.to_s }.map {|a| a.username}.compact
    else
      @last_message_conversation = Managers::MessageManager.get_conversation(current_account, "received", @inbox.first.id)
      @active_id = @inbox.first.id
      @other_part = @inbox.first.sender_id
    end
  end
  
  def new    
    @receivers_usernames = Account.all.select {|a| a.id.to_s != current_account.id.to_s }.map {|a| a.username}.compact
    
    respond_to {|format| format.js }
  end
  
  def create
    @receiver_id = params[:receiver_id] || nil
    @text = params[:text] || nil
    
    @result = nil
    unless @receiver_id.blank? || @text.blank?
      @result = Managers::MessageManager.send_message(current_account, @receiver_id, @text)
      puts "rez #{@result.inspect}"
    end
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def pre_remove
    respond_to {|format| format.js}
  end
  
  def remove
    @message_id = params[:message_id]
    @type = params[:type]
    @result = Managers::MessageManager.delete_message(current_account, @type, @message_id)
    
    respond_to {|format| format.js}
  end
  
  RECEIVED_TYPE = "received"
  SENT_TYPE = "sent"
  def show_next_page
    type = params[:type]
    search_term = params[:search_term] || nil
    from = params[:from] ? params[:from].to_i : 0
    size = params[:size] ? params[:size].to_i : 8
    to = from + size - 1
    sort_by = params[:sort_by] || "date"
    
    if type == RECEIVED_TYPE
      received = Managers::MessageManager.get_messages(current_account, :received, {:search_term => search_term, :from => from, :to => to, :sort_by => sort_by})
      @view = "messages/inbox"
      @container = ".messages.received"
      @params = {:page_inbox => received[:related], :inbox => received[:all], :from => from, :to => received[:to], :active_id => received[:related].empty? ? nil : received[:related].first.id}
      
      if received[:related].empty?
        @receivers_usernames = Account.all.select {|a| a.id.to_s != current_account.id.to_s }.map {|a| a.username}.compact
      else
        @conversation = Managers::MessageManager.get_conversation(current_account, "received", received[:related].empty? ? nil : received[:related].first.id)
        @other_part = received[:related].first.sender_id
      end
    elsif type == SENT_TYPE
      sent = Managers::MessageManager.get_messages(current_account, :sent, {:search_term => search_term, :from => from, :to => to, :sort_by => sort_by})
      @view = "messages/outbox"
      @container = ".messages.sent"
      @params = {:page_outbox => sent[:related], :outbox => sent[:all], :from => from, :to => sent[:to], :active_id => sent[:related].empty? ? nil :sent[:related].first.id}
    
      if sent[:related].empty?
        @receivers_usernames = Account.all.select {|a| a.id.to_s != current_account.id.to_s }.map {|a| a.username}.compact
      else
        @conversation = Managers::MessageManager.get_conversation(current_account, "sent", sent[:related].empty? ? nil : sent[:related].first.id)
        @other_part = sent[:related].first.receiver_id
      end
    end
  end
  
  def show
    @message_id = params[:id] || nil
    @type = params[:type] || nil
    @conversation = Managers::MessageManager.get_conversation(current_account, @type, @message_id)
    @target_message = @conversation.select{|m| m.id.to_s == @message_id }.to_a.first
    @other_part = @type.to_s == "received" ? @target_message.sender_id : @target_message.receiver_id
    
    unless @type.to_s == "sent"
      @read_result = @target_message.date_read.nil? ? Managers::MessageManager.read_message(current_account, @target_message) : nil
    end
    respond_to {|format| format.js }
  end
  
  def reply
    @receiver_id = params[:receiver_id] || nil
    @text = params[:text] || nil
    @reply_to = params[:reply_to] || nil
    
    @result = nil
    unless @receiver_id.blank? || @text.blank?
      @result = Managers::MessageManager.send_message(current_account, @receiver_id, @text, {:reply_to => @reply_to})
      @message = @result[:message]
    end
    respond_to {|format| format.js }
  end
  
  def bulk_delete
    
  end
  
  def receiver_id_remote
    @account_id = Account.where(username: params[:username]).to_a.first.id.to_s
  end
  
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_conversation.html.erb
<div class="conversation">
	<% if conversation.empty? %>
	<div class="muted"><%= I18n.t("messages.conversation_empty") %></div>
	<% else %>
	<% conversation.each do |message| %>
	<%= render :partial => "messages/conversation_item", :locals => {:message => message} %>
	<% end %>
	<% end %>
</div>

app/views/messages/_conversation_item.html.erb
<% css_class = "row-fluid conversation-item" %>
<% css_class = message.sender_id.to_s == current_account.id.to_s ? [css_class, "my"].join(" ") : [css_class, "other"].join(" ") %>
<div class="<%= css_class %>">
	<div class="row-fluid">
		<%= link_to "#", :class => "sender-avatar" do %>
		<%= image_tag message.sender_details["logo"] || message.sender_details["avatar"], :size => "34x34" %>
		<% end %>
		
		<%= link_to "#{message.sender_details['name']} (#{message.sender_details['username']})", "#", :class => "sender-name" %><br/>
		
		<p class=" text"><%= message.text %></p>
	</div>
	
	<div class="date-sent muted">
		<%= [distance_of_time_in_words(message.date_sent.to_time.to_i, Time.now.utc.to_time.to_i, true), "ranije"].join(" ") %>
	</div>
</div>

app/views/messages/_inbox.html.erb
<% if page_inbox.empty? %>
<div class="muted no-messages">
	<%= I18n.t("messages.inbox_empty") %>
</div>
<% else %>
<div class="messages">
<% page_inbox.each do |message| %>
<%= render(:partial => "messages/message_item", :locals => {:message => message, :received => true, :active => !active_id.nil? && active_id.to_s == message.id.to_s }) %>
<% end %>
</div>

<% unless page_inbox == inbox %>
<% prev_class = "messages-paging prev btn btn-mini" %>
<% prev_class = [prev_class, "disabled"].join(" ") if from == 0 %>
<% next_class = "messages-paging next btn btn-mini" %>
<% next_class = [next_class, "disabled"].join(" ") if to == inbox.length - 1  %>
<div class="pagination">
	<div class="pull-right">
		<small class="muted"><%= I18n.t("messages.showing", :from => from + 1, :to => to + 1, :count => inbox.length) %></small>
		<%= link_to "#", :class => prev_class do %>
		<i class="icon-backward"></i>
		<% end %>
		<%= link_to "#", :class => next_class do %>
		<i class="icon-forward"></i>
		<% end %>
	</div>
</div>
<% end %>

<% end %>

app/views/messages/_message_item.html.erb
<% css_class = "row-fluid message-item" %>
<% css_class = [css_class, "active"].join(" ") if active %>
<% css_class = [css_class, "unread"].join(" ") if message.date_read.nil? && received %>
<% other_part = message.sender_id.to_s == current_account.id.to_s ? message.receiver_details : message.sender_details %>

<div class="<%= css_class %>" id="<%= message.id.to_s %>">
	<%= link_to "#", :class => "span2 other_part_avatar" do %>
	<%= image_tag other_part["logo"] || other_part["avatar"], :size => "40x40" %>
	<% end %>
	
	<div class="span10">
		<div class="message-options">
			<input type="checkbox" name="select" class="select-message">
			<%= form_tag(url_for(:controller => "messages", :action => "pre_remove"), :remote => true, :class=>"remove-message") do %>
			<%= hidden_field_tag "message_id", message.id %>
			<%= hidden_field_tag "type", received ? "received" : "sent" %>
			<%= button_tag raw(""), :type => "submit", :class => "icon-remove remove-item" %>
			<% end %>
		</div>
		<div class="row-fluid other_part"><%= link_to "#{other_part['name']} (#{other_part['username']})", "#" %></div>
		<div class="row-fluid text"><%= link_to message.text, url_for(:controller => "messages", :action => "show", :id => message.id, :type => received ? "received" : "sent"), :class => "read-message", :remote => true %></div>
	</div>
</div>

app/views/messages/_messages_container.html.erb
<div class="span4 messages-container messages-left">
	<div class="row-fluid search-sort">
		<div class="pull-left input-append sort-messages">
			<%= link_to "#", :class => "btn btn-mini disabled", :id => "sort_messages_date", :title => I18n.t("sort_by_date") do %>
			<i class="icon-arrow-down"></i><%= I18n.t("date") %>
			<% end %>
			
			<%= link_to "#", :class => "btn btn-mini", :id => "sort_messages_unread", :title => I18n.t("messages.unread_first") do %>
			<i class="icon-arrow-down"></i><%= I18n.t("messages.unread") %>
			<% end %>
		</div>
		<div class="pull-right search">
			<%= text_field_tag "messages_term", "", :class => "input-medium search-query", :placeholder => I18n.t("messages.search_messages") %>
		</div>
	</div>
	
	<div class="row-fluid select-delete">
		<div class="pull-left">
			<label class="checkbox inline">
				<%= check_box_tag "select-all" %><%= I18n.t("select_all") %>
			</label>
		</div>
		
		<div class="pull-right">
			<%= link_to "#", :class => "btn btn-mini delete-messages" do %>
			<i class="icon-remove-sign"></i><%= I18n.t("delete") %>
			<% end %>
		</div>
	</div>
	
	<ul class="nav nav-tabs small">
		<li class="active"><%= link_to I18n.t("messages.received"), "#received", "data-toggle" => "tab", :id => "show-received-messages" %></li>
		<li><%= link_to I18n.t("messages.sent"), "#sent", "data-toggle" => "tab", :id  => "show-sent-messages" %></li>
	</ul>
	
	<div class="tab-content">	
		<div class=" tab-pane active row-fluid messages received" id="received">
			<%= render :partial => "messages/inbox", :locals => {:page_inbox => @inbox, :inbox => @received[:all], :from => 0, :to => @inbox_to, :active_id => @active_id} %>
		</div>
		
		<div class=" tab-pane row-fluid messages sent" id="sent">
			<%= render :partial => "messages/outbox", :locals => {:page_outbox => @outbox, :outbox => @sent[:all], :from => 0, :to => @outbox_to, :active_id => @active_id} %>			
		</div>
	</div>
</div>

app/views/messages/_new.html.erb
<% url = to.nil? ? message_path : url_for(:controller => "messages", :action => "reply") %>

<%= form_tag(url, :remote => true, :class => "send-message", :method => "post") do |f| %>
<%= hidden_field_tag "receiver_id", to %>
<%= hidden_field_tag "reply_to", reply_to %>

<% if to.nil? %>
<%= text_field_tag "receiver", "", 
	:placeholder => I18n.t("messages.receiver"), 
	:class => "message-to",
	:id => "receiver", 
	:autocomplete => "off",
	"data-provide" => "typeahead"
%>

<script type="text/javascript">
	$("#receiver").typeahead({
		source: <%= raw receivers_usernames.to_json %>,
		updater: function(item){
			$.ajax({
	    		type: "POST",
	    		url: "<%= receiver_id_remote_message_path %>", 
	    		data: {username: item},
	    		success: function(data, textStatus, xhr){},
	    		error: function(xhr, textStatus, errorThrown){}
	    	});
			
			return item;
		}
	});
</script>
<% end %>

<div>
	<%= text_area_tag "text", "", :rows => 4, :class=> "span4", :placeholder => I18n.t("messages.type_message") %>
</div>
<div class="pull-right">
	<%= submit_tag I18n.t("messages.send"), :class => "btn btn-success btn-small" %>
</div>
<% end %>

app/views/messages/_outbox.html.erb
<% if page_outbox.empty? %>
<div class="muted no-messages">
	<%= I18n.t("messages.outbox_empty") %>
	<%= link_to I18n.t("messages.new_message"), new_message_path, :remote => true %>
</div>
<% else %>
<div class="messages">
<% page_outbox.each do |message| %>
<%= render(:partial => "messages/message_item", :locals => {:message => message, :received => false, :active => !active_id.nil? && active_id.to_s == message.id.to_s}) %>
<% end %>
</div>

<% unless page_outbox == outbox %>
<% prev_class = "messages-paging prev btn btn-mini" %>
<% prev_class = [prev_class, "disabled"].join(" ") if from == 0 %>
<% next_class = "messages-paging next btn btn-mini" %>
<% next_class = [next_class, "disabled"].join(" ") if to == outbox.length - 1  %>
<div class="pagination">
	<div class="pull-right">
		<small class="muted"><%= I18n.t("messages.showing", :from => from + 1, :to => to + 1, :count => outbox.length) %></small>
		<%= link_to "#", :class => prev_class do %>
		<i class="icon-backward"></i>
		<% end %>
		<%= link_to "#", :class => next_class do %>
		<i class="icon-forward"></i>
		<% end %>
	</div>
</div>
<% end %>

<% end %>

app/views/messages/_pre_remove.html.erb
<div class='modal hide fade remove-confirm'>
	<div class='modal-body'>
		<h5><%= I18n.t("messages.remove_confirm") %></h5>
		<%= form_tag url_for(:action => "remove"), :remote => true do %>
			<%= hidden_field_tag "message_id", params[:message_id] %>
			<%= hidden_field_tag "type", params[:type] %>
			<%= submit_tag I18n.t("confirm"), :class => "btn btn-danger" %>
			<%= button_tag I18n.t("cancel"), :type => "reset", :class => "btn", "data-dismiss" => "modal" %>
		<% end %>
	</div>
</div>

app/views/messages/new.js.erb
var new_message_html = $("<%= escape_javascript(render(:partial => "messages/new", :locals => {:receivers_usernames => @receivers_usernames, :to => nil, :reply_to => nil})) %>");
$(".messages-center").html(new_message_html);

$(".message-item").removeClass("active");

app/views/messages/pre_remove.js.erb
$("<%= escape_javascript(render(:partial => 'messages/pre_remove')) %>").appendTo($("body"));
$(".remove-confirm").modal();

app/views/messages/remove.js.erb
$(".remove-confirm").modal("hide");
$(".remove-confirm").remove();

<% if @result[:status] %>
$("#<%= @message_id %>").remove();
<% else %>
<% end %>

app/views/messages/reply.js.erb
if($("#send_message_loading").length > 0) $("#send_message_loading").remove();

<% if @receiver_id.blank? || @text.blank? %>
$("form.send-message").append($('<div class="text-error message"><small><%= I18n.t("messages.errors.invalid_fields") %></small></div>'));
<% else %>

<% if @result && @result[:status] %>
	var message_html = $("<%= escape_javascript(render(:partial => "messages/conversation_item", :locals => {:message => @message})) %>");
	$(".conversation").append(message_html);
	$("#text").val("");
<% else %>
	<% error = @result ? @result[:text] : I18n.t("messages.errors.common_error") %>
	var html = '<div class="text-error message"><small><%= error %></small></div>';
	$("form.send-message").append($(html));
<% end %>

<% end %>

if($(".message").length > 0){
	setTimeout(function(){
		$(".message").fadeOut(2000, function(){});
	}, 2000);
}

app/views/messages/show.js.erb
var conversation_html = $("<%= escape_javascript(render(:partial => "messages/conversation", :locals => {:conversation => @conversation})) %>");
var new_message_html = $("<%= escape_javascript(render(:partial => "messages/new", :locals => {:receivers_usernames => [], :to => @other_part, :reply_to => @conversation.last.id})) %>");
$(".messages-center").html(conversation_html);
$(".messages-center").append(new_message_html);

$(".message-item").removeClass("active");
$("#<%= @target_message.id %>").removeClass("unread").addClass("active");


app/views/messages/show_next_page.js.erb
var messages_html = $("<%= escape_javascript(render(:partial => @view, :locals => @params)) %>");
$("<%= @container %>").html(messages_html);

<% if @conversation %>
	var conversation_html = $("<%= escape_javascript(render(:partial => "messages/conversation", :locals => {:conversation => @conversation})) %>");
<% else %>
	var conversation_html = "";	
<% end %>
$(".messages-center").html(conversation_html);

var new_message_html = $("<%= escape_javascript(render(:partial => "messages/new", :locals => {:receivers_usernames => [], :to => @other_part, :reply_to => @conversation ? @conversation.last.id : nil})) %>");
$(".messages-center").append(new_message_html);