config/routes.rb
require "heartbeat/application"

Mobis::Application.routes.draw do
  get "home/new"
  get "home/index"
  get "home/about"
  get "home/contact"

  root :to => "home#index"
  
  match "set_js_vars" => "application#set_js_vars", :as => "set_js_vars", :via => :post
  match "get_js_var" => "application#get_js_var", :as => "get_js_var", :via => :post 
  match ":username/katalog" => "catalogues#index", :as => "catalogue"  
  match "unauthorized_access" => "application#unauthorized_access"
  match "show_error" => "application#show_error"
  match "poruke" => "messages#index", :as => "messages"
  match "mobiteli" => "phones#index", :as => "phones"
  
  devise_scope :account do    
    match "registracija" => "accounts/registrations#index", :as => "register", :via => :get
    match "registracija_korisnika" => "accounts/registrations#new", :account => { :type => "user" }, :as => "register_user"
    match "registracija_prodavnice" => "accounts/registrations#new", :account => { :type => "store" }, :as => "register_store"
    match "registracija" => "accounts/registrations#create", :as => "registration", :method => :post  
  
  end
  
  devise_for :accounts, :controllers => {
    :sessions => "accounts/sessions",
    :passwords => "devise/passwords"
  },
  :path => "",
  :path_names => {:sign_in => "prijava", :sign_out => "odjava", :new_unlock => "promijeni_sifru"}
  
  namespace :api do
    namespace :v1 do      
      match "chat/config" => "chat#get_conf", via: :get
      
      mount Api::V1::Phones, :at => "/mobiteli"
      mount Api::V1::Messages, :at => "/poruke"
      mount Api::V1::Catalogue, :at => "/katalog"
    end
  end
  
  namespace :admin do
    match "korisnici" => "users#list_users", :as => "users"
    match "users/lock" => "users#lock_user", via: :post
    
    resources :phones, :only => [:new, :edit, :create, :update, :destroy]
    match "phones/add/:id" => "phones#add", via: :post, :as => "phone_add"
    match "mobiteli" => "phones#list_phones", via: :get, :as => "phones"
    match "mobiteli/atributi" => "phones#attributes", via: :get, :as => "phones_attributes"
    match "phones_add_attribute" => "phones#add_attribute", via: :post
    match "mobiteli/import" => "phones#import_phones", via: :get
    match "phones/import" => "phones#import", via: :post, :as => "phones_import_phones"
    match "phones/import_images" => "phones#import_images", via: :post
    match "mobiteli/reindex" => "phones#reindex", via: :get, :as => "phones_reindex"
    
    resource :phones, :only => [:create, :new] 
  end
  
  resources :phones, :only => [:show]
  resources :comments, :only => [:create] do
    collection do
      match "show_next_page", :action => "show_next_page", :via => :post
      get "new/:phone_id", :action => "new"
    end
    member do
      post "", :action => "create"
    end
  end
  
  resource :reviews, :only => [] do
    member do
      post "create_phone_review", :action => "create_phone_review"
    end
  end
  
  resource :catalogue, :only => [:new, :update, :edit] do
    match "show_next_page", :action => "show_next_page", :via => :post
    match "pre_remove", :action => "pre_remove"
    match "remove", :action => "remove", via: :post
    match "phone_details_remote", :action => "phone_details_remote", via: :post
  end
  
  resource :message, :only => [:index, :new, :create, :update, :edit] do
    match "/:type/:id", :action => "show", :via => "get"
    match "show_next_page", :action => "show_next_page", :via => :post
    match "bulk_delete", :action => "bulk_delete", :via => :post
    match "receiver_id_remote", :action => "receiver_id_remote", :via => :post
    match "pre_remove", :action => "pre_remove", :via => "post"
    match "remove", :action => "remove", :via => "post"
    match "reply", :action => "reply", :via => "post"
  end
  
  resource :search, :only => [:index], :controller => "search" do
    collection do
      get "index"
      post "index"
      get "search_phones"
      post "search_phones"
      get "advanced_search"
      post "advanced_search"
    end
  end
    
  match "/postavke" => "accounts#show", :as => "settings", :via => "get"
  match "/remove_settings" => "accounts#remove", :as => "settings_remove", :via => :delete
  match "/add_settings" => "accounts#add", :as => "settings_add", :via => :put
  match "/change_password" => "accounts#change_password", :as => "change_password", :via => :post
  match "/accounts_details" => "accounts#accounts_details", :as => "accounts_details", :via => :post  
  match "settings/change_avatar" => "accounts#change_avatar", :as => "change_avatar", :via => :post
 
  match "mobiteli/:brand" => "phones#index", :as => "brand", :via => "get"
  
  mount Heartbeat::Application, :at => "/heartbeat"  
end

app/views/shared/_brands_sidebar.html.erb
<ul class="nav nav-tabs nav-stacked main-brands-list">
	<% brands.each do |brand| %>
	<li><%= link_to(brand, params[:action].to_s == "show" ? brand_path(:brand => brand) : "#") %></li>
	<% end %>
</ul>

app/views/shared/_error.html.erb
<div id="ErrorPopup" class="modal hide fade">
  <div class="modal-body">
  	<p class="text-error">
  		There was an error. Please try later.
  	</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/shared/_login.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :html => { 'data-type' => "html", :id => "login_form", :class => "login-form" }) do |f| %>
	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
  	<%= f.password_field :password %>

	<div>
		<%= f.label :remember_me %>
		<%= f.check_box :remember_me %>
	</div>

	<div>
  		<%= f.submit I18n.t("login.sign_in"), :class => "btn btn-primary login-btn" %>
  	</div>
  
	<div>
		<div class="controls"><%= render :partial => "accounts/shared/links", :locals => {:resource_name => resource_name, :controller_name => "sessions", :resource_class => resource_name.to_s.downcase.camelize.constantize.new} %></div>
	</div>
<% end %>

app/views/shared/_not_authorized.html.erb
<div id="notAuthorizedPopup" class="modal hide fade">
  <div class="modal-body">
  	<p>
  		<%= I18n.t("unauthorized_access") %>
  		Molimo da se&nbsp;
  		<%= link_to(I18n.t("please_login"), new_account_session_path) %>
  		&nbsp;ili&nbsp;
  		<%= link_to(I18n.t("please_register"), register_path) %>
  	</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><%= I18n.t("ok") %></button>
  </div>
</div>

app/views/shared/_search_options.html.erb
<div class="row-fluid options-box">
	
	<div class="row-fluid">
		<div class="span9 btn-group sort-phones-by">
			<%= link_to "#", :class => "btn btn-medium disabled", :title => I18n.t("search.sort_by_date"), :id => "date" do %>
			<i class='icon-arrow-up'></i><%= I18n.t("search.sort_by_date") %>
			<% end %>
			<%= link_to "#", :class => "btn btn-medium", :title => I18n.t("search.sort_by_relevance"), :id => "relevance" do %>
			<i class='icon-arrow-down'></i><%= I18n.t("search.sort_by_relevance") %>
			<% end %>
			<%= link_to "#", :class => "btn btn-medium", :title => I18n.t("search.sort_by_price"), :id => "price" do %>
			<i class='icon-arrow-up'></i><%= I18n.t("search.sort_by_price") %>
			<% end %>
		</div>
		
		<div class="span2">
			<%= text_field_tag "search_term", @search_term, :class => "input-medium", :placeholder => I18n.t("search.search_phones") %>
		</div>
		
		<%= hidden_field_tag(:brand_param, @brand) %>
	</div>
	
	<a href="#" class="pull-left show-price-range"><%= I18n.t("search.filter_by_price_range") %></a>
	
	<%= link_to I18n.t("search.advanced_search"), "#", :class => "show-advanced-search", "data-toggle" => "dropdown" %>
	
	<a href="#" class="pull-right show-all-phones"><i class="icon-repeat"></i><%= I18n.t("search.show_all") %></a>
	
	<div class="advanced-search hide" id="advanced_search">
		<div class="well criteria-group">
			<div class="criteria">
				<%= label_tag "operating_system", I18n.t("mongoid.attributes.phone.os") %>
				<%= select_tag "operating_system", options_from_collection_for_select(@search_options[:os], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "weight", I18n.t("mongoid.attributes.phone.weight") %>
				<%= select_tag "weight", options_from_collection_for_select(@search_options[:weight], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "brand", I18n.t("mongoid.attributes.phone.brand") %>
				<%= select_tag "brand", options_from_collection_for_select(@search_options[:brand], "first", "last") %>
			</div>
		</div>
		<div class="criteria-group well">
			<div class="criteria">
				<%= label_tag "internal_memory", I18n.t("mongoid.attributes.phone.internal_memory") %>
				<%= select_tag "internal_memory", options_from_collection_for_select(@search_options[:internal_memory], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "external_memory", I18n.t("mongoid.attributes.phone.external_memory") %>
				<%= select_tag "external_memory", options_from_collection_for_select(@search_options[:external_memory], "first", "last") %>
			</div>
		</div>
		<div class="criteria-group well">
			<div class="criteria">
				<%= label_tag "camera_mpx", I18n.t("mongoid.attributes.phone.camera.mpx") %>
				<%= select_tag "camera_mpx", options_from_collection_for_select(@search_options[:camera][:mpx], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "camera_blic", I18n.t("mongoid.attributes.phone.camera.blic") %>
				<%= select_tag "camera_blic", options_from_collection_for_select(@search_options[:camera][:blic], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "camera_video", I18n.t("mongoid.attributes.phone.camera.video") %>
				<%= select_tag "camera_video", options_from_collection_for_select(@search_options[:camera][:video], "first", "last") %>
			</div>
			<div class="criteria">
				<%= label_tag "camera_front", I18n.t("mongoid.attributes.phone.camera.front") %>
				<%= select_tag "camera_front", options_from_collection_for_select(@search_options[:camera][:front], "first", "last") %>
			</div>
		</div>
		<div class="row-fluid">
			<%= link_to "Odustani", "#", :class => "btn pull-left", :id => "cancel_advanced_search" %>
			<%= button_tag "Trazi", :class => "btn pull-right", :id => "apply_advanced_search" %>
		</div>
	</div>

	<div class="advanced-search hide" id="price_range_wrapper">
		<div class="span11">
			<div id="price-slider"></div>
			<div class="row-fluid">
				<div class = "pull-left">
					<span class="price-from-text">0</span>
					<span>&nbsp;&nbsp;-&nbsp;&nbsp;</span>
					<span class="price-to-text">0</span>
					<span>&nbsp;$</span>
				</div>
				<div class="pull-right" id="price_range_actions">
					<%= link_to I18n.t("cancel"), "#", :class => "btn btn-mini", :id => "close_price_ranges", :title => I18n.t("cancel") %>
					<%= link_to I18n.t("confirm"), "#", :class => "btn btn-mini", :id => "apply_prices", :title => I18n.t("search.apply_price_range") %>
				</div>
			</div>
		</div>
		<%= hidden_field_tag("price_from", "") %>
		<%= hidden_field_tag("price_to", "") %>
	</div>
	
</div>

app/views/shared/_signed_in_links.html.erb
<%
	@links = {
      :admin => [
        { :name  => I18n.t("header.users"), :url => admin_users_path, :icon => "fa fa-users" },
        { :name  => I18n.t("header.phones"), :url => admin_phones_path, :icon => "fa fa-phone" },
        { :name  => I18n.t("header.catalogue"), :url => catalogue_path(:username => current_account.username), :icon => "icon-list icon-white" },
        { :name => I18n.t("header.messages"), :url => messages_path, :icon => "icon-envelope icon-white" }
      ],
      :store => [
        { :name  => I18n.t("header.catalogue"), :url => catalogue_path(:username => current_account.username), :icon => "icon-list icon-white" },
        { :name => I18n.t("header.messages"), :url => messages_path, :icon => "icon-envelope icon-white" }
      ],
      :user => [
        { :name  => I18n.t("header.catalogue"), :url => catalogue_path(:username => current_account.username), :icon => "icon-list icon-white" },
        { :name => I18n.t("header.messages"), :url => messages_path, :icon => "icon-envelope icon-white" }
      ]
    }
%>
 
<% 		@links[current_account.rolable.class.name.downcase.to_sym].each do |item| %>
<%=       content_tag(:li) do %>
<%=          link_to item[:url] do %>
				<i class="<%= item[:icon] %>"></i><%= item[:name] %>
<% 			 end %>
<%        end %>
<%      end %>