config/routes.rb
require "heartbeat/application"

Mobis::Application.routes.draw do
  get "home/new"
  get "home/index"
  get "home/about"
  get "home/contact"

  root :to => "home#index"
  
  match "set_js_vars" => "application#set_js_vars", :as => "set_js_vars", :via => :post
  match "get_js_var" => "application#get_js_var", :as => "get_js_var", :via => :post 
  match ":username/katalog" => "catalogues#index", :as => "catalogue"  
  match "unauthorized_access" => "application#unauthorized_access"
  match "show_error" => "application#show_error"
  match "poruke" => "messages#index", :as => "messages"
  match "mobiteli" => "phones#index", :as => "phones"
  
  devise_scope :account do    
    match "registracija" => "accounts/registrations#index", :as => "register", :via => :get
    match "registracija_korisnika" => "accounts/registrations#new", :account => { :type => "user" }, :as => "register_user"
    match "registracija_prodavnice" => "accounts/registrations#new", :account => { :type => "store" }, :as => "register_store"
    match "registracija" => "accounts/registrations#create", :as => "registration", :method => :post  
  
  end
  
  devise_for :accounts, :controllers => {
    :sessions => "accounts/sessions",
    :passwords => "devise/passwords"
  },
  :path => "",
  :path_names => {:sign_in => "prijava", :sign_out => "odjava", :new_unlock => "promijeni_sifru"}
  
  namespace :api do
    namespace :v1 do      
      match "chat/config" => "chat#get_conf", via: :get
      
      mount Api::V1::Phones, :at => "/mobiteli"
      mount Api::V1::Messages, :at => "/poruke"
      mount Api::V1::Catalogue, :at => "/katalog"
    end
  end
  
  namespace :admin do
    match "korisnici" => "users#list_users", :as => "users"
    match "users/lock" => "users#lock_user", via: :post
    
    resources :phones, :only => [:new, :edit, :create, :update, :destroy]
    match "phones/add/:id" => "phones#add", via: :post, :as => "phone_add"
    match "mobiteli" => "phones#list_phones", via: :get, :as => "phones"
    match "mobiteli/atributi" => "phones#attributes", via: :get, :as => "phones_attributes"
    match "phones_add_attribute" => "phones#add_attribute", via: :post
    match "mobiteli/import" => "phones#import_phones", via: :get
    match "phones/import" => "phones#import", via: :post, :as => "phones_import_phones"
    match "phones/import_images" => "phones#import_images", via: :post
    match "mobiteli/reindex" => "phones#reindex", via: :get, :as => "phones_reindex"
    
    resource :phones, :only => [:create, :new] 
  end
  
  resources :phones, :only => [:show]
  resources :comments, :only => [:create] do
    collection do
      match "show_next_page", :action => "show_next_page", :via => :post
      get "new/:phone_id", :action => "new"
    end
    member do
      post "", :action => "create"
    end
  end
  
  resource :reviews, :only => [] do
    member do
      post "create_phone_review", :action => "create_phone_review"
    end
  end
  
  resource :catalogue, :only => [:new, :update, :edit] do
    match "show_next_page", :action => "show_next_page", :via => :post
    match "pre_remove", :action => "pre_remove"
    match "remove", :action => "remove", via: :post
    match "phone_details_remote", :action => "phone_details_remote", via: :post
  end
  
  resource :message, :only => [:index, :new, :create, :update, :edit] do
    match "/:type/:id", :action => "show", :via => "get"
    match "show_next_page", :action => "show_next_page", :via => :post
    match "bulk_delete", :action => "bulk_delete", :via => :post
    match "receiver_id_remote", :action => "receiver_id_remote", :via => :post
    match "pre_remove", :action => "pre_remove", :via => "post"
    match "remove", :action => "remove", :via => "post"
    match "reply", :action => "reply", :via => "post"
  end
  
  resource :search, :only => [:index], :controller => "search" do
    collection do
      get "index"
      post "index"
      get "search_phones"
      post "search_phones"
      get "advanced_search"
      post "advanced_search"
    end
  end
    
  match "/postavke" => "accounts#show", :as => "settings", :via => "get"
  match "/remove_settings" => "accounts#remove", :as => "settings_remove", :via => :delete
  match "/add_settings" => "accounts#add", :as => "settings_add", :via => :put
  match "/change_password" => "accounts#change_password", :as => "change_password", :via => :post
  match "/accounts_details" => "accounts#accounts_details", :as => "accounts_details", :via => :post  
  match "settings/change_avatar" => "accounts#change_avatar", :as => "change_avatar", :via => :post
 
  match "mobiteli/:brand" => "phones#index", :as => "brand", :via => "get"
  
  mount Heartbeat::Application, :at => "/heartbeat"  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_join_us.html.erb
<div class="hero-unit">
	<h3>Novi svijet poslovanja sa mobis.ba</h3>
	<p>
		
	</p>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<div>
	<img src="/carousel1.jpg" />
	
	<div class="logo">
		<h2>Mobis</h2>
	</div>
	
	<div class="login-account-info">
		<%  if account_signed_in? %>
		<%= link_to "Katalog mobitela", phones_path, :class => "btn" %>
		<%= link_to "#{current_account.username} [Logout]", destroy_account_session_path, :method => :delete, :class => "btn" %>
		<% else %>
		<%= form_tag(account_session_path, :class => "form-inline login-form") do %>
		<%= text_field_tag "account[email]", "", :placeholder => "Email", :class => "input" %>
		<%= password_field_tag "account[password]", "", :placeholder => "Password", :class => "input" %>
		<%= button_tag "Login", :type => "submit", :class => "btn btn-info" %>
		<% end %>
		<% end %>
	</div>
	
	<div class="homepage-search">
		<form action="<%= phones_path %>" method="GET">
		<div class="input-append">
			<%= text_field_tag "search_term", "", :placeholder => I18n.t("home.search_placeholder") %>
			<%= button_tag I18n.t("search.search"), :type => "submit", :class => "btn btn-warning", :name => nil %>
		</div>
		</form>
		<%= link_to I18n.t("home.list_all_phones"), phones_path, :class => "list-all-phones" %>
	</div>
	
	<div class="homepage-actions">
		<%= link_to I18n.t("home.register_user"), register_user_path, :class => "btn btn-large btn-primary" %>
		<%= link_to I18n.t("home.register_store"), register_store_path, :class => "btn btn-large btn-success" %>
	</div>
	
	<div class="slider">
		<div class="slider-content">
			<div class="slider-item active">
				<h1>Pronađite mobitel za vas</h1>
				<p class="lead">
					Ponuda od preko 2000 modela mobilnih telefona.<br/>
					Svaki dan 100 novih ponuda u katalozima.</br>
					Novi i polovni mobitela svih generacija.					
				</p>
			</div>
			
			<div class="slider-item">
				<h1>Prodajte mobitel.</h1>
				<p class="lead">
					Napravite svoj profil ili profil radnje koju vodite.<br/>
					Postavljajte nove ili polovne mobitele u svoj katalog.</br>
					Jednostavno. Ucinkovito. Besplatno.					
				</p>
			</div>
			
			<div class="slider-item">
				<h1>Komunicirajte ucinkovito.</h1>
				<p class="lead">
					Chat uzivo sa drugim korisnicima i prodavnicama.<br/>
					Razmjena poruka sa korisnicima.</br>
					Dodjite brzo do onoga sto trazite.					
				</p>
			</div>
			
			<a class="slider-navigation left" href="#" data-slide-to="prev">&lsaquo;</a>
		  	<a class="slider-navigation right" href="#" data-slide-to="next">&rsaquo;</a>
		</div>
	</div>
</div>

app/views/home/new.html.erb
<h1>Home#new</h1>
<p>Find me in app/views/home/new.html.erb</p>