config/routes.rb
require "heartbeat/application"

Mobis::Application.routes.draw do
  get "home/new"
  get "home/index"
  get "home/about"
  get "home/contact"

  root :to => "home#index"
  
  match "set_js_vars" => "application#set_js_vars", :as => "set_js_vars", :via => :post
  match "get_js_var" => "application#get_js_var", :as => "get_js_var", :via => :post 
  match ":username/katalog" => "catalogues#index", :as => "catalogue"  
  match "unauthorized_access" => "application#unauthorized_access"
  match "show_error" => "application#show_error"
  match "poruke" => "messages#index", :as => "messages"
  match "mobiteli" => "phones#index", :as => "phones"
  
  devise_scope :account do    
    match "registracija" => "accounts/registrations#index", :as => "register", :via => :get
    match "registracija_korisnika" => "accounts/registrations#new", :account => { :type => "user" }, :as => "register_user"
    match "registracija_prodavnice" => "accounts/registrations#new", :account => { :type => "store" }, :as => "register_store"
    match "registracija" => "accounts/registrations#create", :as => "registration", :method => :post  
  
  end
  
  devise_for :accounts, :controllers => {
    :sessions => "accounts/sessions",
    :passwords => "devise/passwords"
  },
  :path => "",
  :path_names => {:sign_in => "prijava", :sign_out => "odjava", :new_unlock => "promijeni_sifru"}
  
  namespace :api do
    namespace :v1 do      
      match "chat/config" => "chat#get_conf", via: :get
      
      mount Api::V1::Phones, :at => "/mobiteli"
      mount Api::V1::Messages, :at => "/poruke"
      mount Api::V1::Catalogue, :at => "/katalog"
    end
  end
  
  namespace :admin do
    match "korisnici" => "users#list_users", :as => "users"
    match "users/lock" => "users#lock_user", via: :post
    
    resources :phones, :only => [:new, :edit, :create, :update, :destroy]
    match "phones/add/:id" => "phones#add", via: :post, :as => "phone_add"
    match "mobiteli" => "phones#list_phones", via: :get, :as => "phones"
    match "mobiteli/atributi" => "phones#attributes", via: :get, :as => "phones_attributes"
    match "phones_add_attribute" => "phones#add_attribute", via: :post
    match "mobiteli/import" => "phones#import_phones", via: :get
    match "phones/import" => "phones#import", via: :post, :as => "phones_import_phones"
    match "phones/import_images" => "phones#import_images", via: :post
    match "mobiteli/reindex" => "phones#reindex", via: :get, :as => "phones_reindex"
    
    resource :phones, :only => [:create, :new] 
  end
  
  resources :phones, :only => [:show]
  resources :comments, :only => [:create] do
    collection do
      match "show_next_page", :action => "show_next_page", :via => :post
      get "new/:phone_id", :action => "new"
    end
    member do
      post "", :action => "create"
    end
  end
  
  resource :reviews, :only => [] do
    member do
      post "create_phone_review", :action => "create_phone_review"
    end
  end
  
  resource :catalogue, :only => [:new, :update, :edit] do
    match "show_next_page", :action => "show_next_page", :via => :post
    match "pre_remove", :action => "pre_remove"
    match "remove", :action => "remove", via: :post
    match "phone_details_remote", :action => "phone_details_remote", via: :post
  end
  
  resource :message, :only => [:index, :new, :create, :update, :edit] do
    match "/:type/:id", :action => "show", :via => "get"
    match "show_next_page", :action => "show_next_page", :via => :post
    match "bulk_delete", :action => "bulk_delete", :via => :post
    match "receiver_id_remote", :action => "receiver_id_remote", :via => :post
    match "pre_remove", :action => "pre_remove", :via => "post"
    match "remove", :action => "remove", :via => "post"
    match "reply", :action => "reply", :via => "post"
  end
  
  resource :search, :only => [:index], :controller => "search" do
    collection do
      get "index"
      post "index"
      get "search_phones"
      post "search_phones"
      get "advanced_search"
      post "advanced_search"
    end
  end
    
  match "/postavke" => "accounts#show", :as => "settings", :via => "get"
  match "/remove_settings" => "accounts#remove", :as => "settings_remove", :via => :delete
  match "/add_settings" => "accounts#add", :as => "settings_add", :via => :put
  match "/change_password" => "accounts#change_password", :as => "change_password", :via => :post
  match "/accounts_details" => "accounts#accounts_details", :as => "accounts_details", :via => :post  
  match "settings/change_avatar" => "accounts#change_avatar", :as => "change_avatar", :via => :post
 
  match "mobiteli/:brand" => "phones#index", :as => "brand", :via => "get"
  
  mount Heartbeat::Application, :at => "/heartbeat"  
end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Paperclip
  
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :lockable
  
  field :username, :type => String
  
  belongs_to :rolable, polymorphic: true

  has_and_belongs_to_many :following, class_name: 'Account', inverse_of: :followers, autosave: true
  has_and_belongs_to_many :followers, class_name: 'Account', inverse_of: :following
  
  has_and_belongs_to_many :phone_followings, class_name: 'Phone'  
  has_many :comments
  
  embeds_many :received_messages, class_name:  "Message", inverse_of: :receiver
  embeds_many :sent_messages, class_name:  "Message", inverse_of: :sender
  
  validates :username, length: {minimum: 6, maximum: 20}
    
  def unread_messages
    received_messages.select {|m| m.date_read.nil? }
  end
end
  

app/controllers/accounts/registrations_controller.rb
class Accounts::RegistrationsController < Devise::RegistrationsController
  
  def index
    
  end
  
  def create
    build_resource
    account_type = params[:account][:type].to_sym
    params[params[:account][:type].to_sym][:phone] = params[account_type][:phone] ? [params[account_type][:phone]] : []
    params[params[:account][:type].to_sym][:address] = params[account_type][:address] ? [params[account_type][:address]] : []

    rolable = params[:account][:type].downcase.camelize.constantize.new(params[params[:account][:type].to_sym])
    resource.rolable = rolable
    resource.username = form_username(resource.email) unless resource.email.blank?
    
    valid = rolable.valid? && resource.valid?
    
    rolable.errors.messages.each do |attribute, message|
      unless attribute == :account
        hsh = {}
        hsh[attribute] = message
        resource.errors.messages.merge!(hsh)
      end
    end

    if valid && resource.save && resource.rolable.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      address = resource.rolable.address.select { |addr| !addr.blank? }.compact
      resource.rolable.address = address.blank? ? nil : address
      phone = resource.rolable.phone.select { |pho| !pho.blank? }.compact
      resource.rolable.phone = phone.blank? ? nil : phone
      
      clean_up_passwords resource
      respond_with resource
    end
  end
  
  def new
    super
  end
  
end

app/controllers/accounts/sessions_controller.rb
class Accounts::SessionsController < Devise::SessionsController

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
        
    respond_with resource, :location => after_sign_in_path_for(resource)
  end
  
   def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    current_account = session[:current_account]
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_navigational_format?
    
    # hack for chat disconnect
    session[:current_account] = current_account
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to redirect_path }
    end
  end
  
  protected
  
  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { :methods => methods, :only => [:password] }
  end

  def auth_options
    { :scope => resource_name, :recall => "#{controller_path}#new" }
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  DEFAULT_LOGO = "/images/no_image.jpg"
  def accounts_details
    ids = params[:id].flatten
    
    accounts = []
    ids.each do |id|
      acc = Account.find(id)
      rolable = acc.rolable
      accounts << {:id => acc.id.to_s, :username => acc.username, :name => rolable.name, :image => rolable.logo.exists? ? rolable.logo.url : DEFAULT_LOGO, :email => acc.email}
    end
    
    render accounts.to_json
  end
  
  def show
    @account_info = AccountDecorator.decorate(current_account).get_info
  end
  
  FILTER_PROPERTIES = ["authenticity_token", "utf8", "controller", "action", "_method"]
  def remove
    properties_to_remove = params.clone
    properties_to_remove.delete_if { |name, value| FILTER_PROPERTIES.include?(name.to_s) }
    properties_to_remove = Hash[properties_to_remove.map { |name, value| [name.to_s.split("_").first, value] }]
    
    remove_result = Managers::AccountManager.remove(current_account, properties_to_remove)
    if remove_result[:status]
      render :json => {:message => remove_result[:message], :attributes => remove_result[:attributes]}, :status => 200
    else
      render :json => {:message => remove_result[:message]}, :status => 400
    end
    
  end
  
  def add
    properties_to_add = params.clone
    properties_to_add.delete_if { |name, value| FILTER_PROPERTIES.include?(name.to_s) }
    properties_to_add = Hash[properties_to_add.map { |name, value| [name.to_s.split("_").first, value] }]
    
    add_result = Managers::AccountManager.add(current_account, properties_to_add)
    if add_result[:status]
      render :json => {:message => add_result[:message], :attributes => add_result[:attributes]}, :status => 200
    else
      render :json => add_result[:message], :status => 400
    end
  end
  
  def change_password
    if current_account.valid_password?(params[:old_password])
      if current_account.reset_password!(params[:new_password], params[:password_confirmation])
        current_account.save
        sign_in(current_account, :bypass => true)
        render :json => {:message => "Sifra promijenjena"}, :status => 200
      else
        render :json => "Neispravan format sifre. Sifra mora imati bar 6 znakova. Potvrda sifre se mora poklapati sa sifrom", :status => 400
      end
    else
      render :json => "Pogresna sifra", :status => 400
    end
  end
  
  ALLOWED_AVATAR_EXTENSIONS = [".jpg", ".jpeg", ".png", ".gif"]
  MAX_AVATAR_SIZE = 4000000
  def change_avatar
    if(params[:avatar].size > MAX_AVATAR_SIZE)
      render :json => I18n.t("accounts.file_too_big_error", max_size: MAX_AVATAR_SIZE/1000000), :status => 400
      return
    end
    
    file_extension = File.extname(params[:avatar].original_filename).strip.downcase
    unless ALLOWED_AVATAR_EXTENSIONS.include?(file_extension)
      render :json => I18n.t("accounts.file_bad_extension_error", allowed_extensions: ALLOWED_AVATAR_EXTENSIONS.join(", ")), :status => 400
      return
    end
    
    current_account.rolable.avatar = params[:avatar]
    if current_account.save && current_account.rolable.save
      current_account.reload
      render :json => {:status => "success", :avatar => AccountDecorator.decorate(current_account).get_avatar }, :status => 200
    else
      render :json => I18n.t("accounts.change_avatar_error"), :status => 400
    end
  end
  
end

app/helpers/account_helper.rb
module AccountHelper
  
  MIN_USERNAME_LENGTH = 6
  #TODO: filter chars that are not allowed
  FORBIDDEN_USERNAME_CHARS = /\?|\<|\>|\'|\.|\,|\?|\[|\]|\}|\{|\=|\)|\(|\*|\&|\|^|\%|\$|\#|\`|\~|/
  def form_username(email)
    formed_username = email.split("@")[0]
    formed_username = formed_username.gsub(FORBIDDEN_USERNAME_CHARS, "")
    
    return formed_username if formed_username.length >= MIN_USERNAME_LENGTH
    
    size = MIN_USERNAME_LENGTH - formed_username.length    
    while true
      formed_username = [formed_username, (1..size).to_a].flatten.join
      break if Account.where(username: formed_username).to_a.empty?
      size = size + 1
    end
    formed_username
  end
  
  def property_editable?(property)
    Managers::AccountManager.editable?(property)
  end
  
end

app/views/accounts/_account_info_value.html.erb
<% if value.is_a?(Array) %>
	<%= form_tag(settings_remove_path, :method => :delete, :remote => true, :class => "remove-property", :"data-type" => "json") do %>
	<%= hidden_field_tag [property, "remove"].join("_"), "" %>
	<% end %>
	<div class="values">
		<% value.each do |val| %>
			<div class="label label-info value-wrapper">
				<span><%= val %></span>
				<%= link_to "", "#", :class => "icon-remove remove-property", :"data-property" => property %>
			</div>
		<% end %>
	</div>
<% else %>
	<div class="values">
		<%= value %>
	</div>
<% end %>

app/views/accounts/show.html.erb
<div class="account-settings">
	<ul class="nav nav-pills">
		<li class="active">
			<a class="toggle-tab-account-settings" href="#account_info" data-toggle="pill">
		    	<%= I18n.t("accounts.account_info_tab_title") %>
			</a>
		</li>
		<li>
		  	<a class="toggle-tab-account-settings" href="#change_password" data-toggle="pill">
		    	<%= I18n.t("accounts.change_password_tab_title") %>
		  	</a>
		</li>
	</ul>     
    
    
    <div class="tab-content">
	    <div id="account_info" class="tab-pane active account-info thumbnail">
			<div class="row-fluid">
				<div class="span10">
					<table class="table table-hover account-attributes">
						<tbody>
						<% @account_info.each do |attr, details| %>
							<% if  attr != :name && attr != :avatar && details[:display] %>
								<% css_class = [details[:value].blank? ? "warning" : "success", [attr, "info"].join("-")].join(" ") %>
								<tr class="<%= css_class %>">
								<td class="attribute-name"><%= details[:label] %></td>
						  		<td class="attribute-value">
						  			<%= render :partial => "account_info_value", :locals => {:property => attr, :value => details[:value]} %>
						  		</td>
						  		<td class="update-attribute">
						  			<% if property_editable?(attr) %>
							  			<%= link_to("", "#", :class => "icon-edit toggle-property", :"data-property" => attr) %>
							  			<%= link_to("", "#", :class => "pull-right icon-ok add-property hidden", :"data-property" => attr) %>
							  			<%= form_tag(settings_add_path, :method => :put, :remote => true, :class => "form-inline add-property hidden", :"data-type" => "json") do %>
							  			<%= text_field_tag [attr.to_s, "add"].join("_"), "" %>
							  			<% end %>
							  		<% else %>
							  			<small class="text-info"><%= details[:label] %> se ne moze promijeniti</small>
							  		<% end %>
						  		</td>
						  		</tr>
						  	<% end %>
						<% end %>
						</tbody>
					</table>
				</div>
				<div class="span2 settings-avatar-container">
					<%= form_tag(change_avatar_path, :method => :post, :remote => true, :class => "change-avatar-form", :multipart => true) do %>
					<%= file_field_tag "avatar", :"data-url" => change_avatar_path %>
					<% end %> 
					<div class="avatar-wrapper clearfix">
						<%= image_tag @account_info[:avatar][:value], :class => "pull-right image-rounded account-settings-avatar" %>
						<%= link_to "", "#", :class => "change-avatar icon-upload", :title => I18n.t("accounts.change_avatar") %>
					</div>
				</div>
			</div>
	    </div>
	
	    <div id="change_password" class="tab-pane thumbnail">
	        <%= form_tag(change_password_path, :method => :post, :remote => true, :"data-type" => "json", :class => "change-password") do %>
	        <div>
	        	<%= label_tag("old_password", "Stara sifra") %>
	        	<%= password_field_tag "old_password" %>
	        </div>
	        <div>
	        	<%= label_tag("new_password", "Nova sifra") %>
	        	<%= password_field_tag "new_password" %>
	        </div>
	        <div>
	        	<%= label_tag("password_confirmation", "Potvrdite sifru") %>
	        	<%= password_field_tag "password_confirmation" %>
	        </div>
	        <div>
	        	<%= submit_tag "Promijeni sifru", :class => "btn pull-right" %>
	        </div>
	        <% end %>
	    </div>
	</div>
    
</div>